jobs:
  - name: u14-image
    type: runSh
    steps:
      - TASK:
          runtime:
            options:
              imageName: "drydock/u14"
              imageTag: master
          script:
            
             - java -version  
             - nodejs --version
             - yarn -version
             - source /usr/local/rvm/scripts/rvm
             - ruby -v
             - python -V
             - pip --version
             - virtualenv --version
             - git --version
             - aws --version
             - az --version
             - jfrog --version
             - gcloud version
             - git lfs version
             - kubectl version --client
             - kops version
             - helm version --client
             - doctl version
             - ansible --version
             - pip show boto
             - pip show boto3
             - pip show apache-libcloud
             - pip show azure
             - pip show dopy
             - packer --version
             - jq --version
             - terraform --version
             - openstack --version
             - eb --version
            
             
  - name: u14all-image
    type: runSh
    steps:
      - IN: u14-image
      - TASK:
          runtime:
            options:
              imageName: "drydock/u14all"
              imageTag: master
          script:
         
            - elasticsearch --version
            - memcached --version
            - cassandra -v
            - riak version
            - service couchdb start
            - sleep 5
            - curl http://127.0.0.1:5984  
            - psql --version
            - java -jar /usr/local/selenium/selenium-server-standalone-3.11.0.jar --version
            - sqlite3 --version
            - mysql --version
            - mongod --version
            - /var/lib/neo4j/bin/neo4j version
            - dpkg -s rabbitmq-server | grep Version
            - redis-server --version

  - name: golang-test
    type: runSh
    runtime:
      container: true
    steps:
      - IN: u14all-image
      - TASK:
            runtime:
              options:
                imageName: "drydock/u14golall"
                imageTag: master
                script:
                  - source /root/.gvm/scripts/gvm
                  - gvm list
                  - gvm use 1.4
                  - go version
                  - gvm use 1.7.6
                  - go version
                  - gvm use 1.8.7
                  - go version
                  - gvm use 1.9.6
                  - go version
                  - gvm use 1.10.2
                  - go version

  - name: php-test
    type: runSh
    steps:
      - IN: u14all-image
      - TASK:
         runtime:
          options:
            imageName: "drydock/u14phpall"
            imageTag: master
        script: 
         - php --version
         - ~/.phpenv/versions/5.6/bin/php -v
         - ~/.phpenv/versions/5.6/bin/phpunit --version
         - ~/.phpenv/versions/7.0/bin/php -v
         - ~/.phpenv/versions/7.0/bin/phpunit --version
         - ~/.phpenv/versions/7.1/bin/php -v
         - ~/.phpenv/versions/7.1/bin/phpunit --version
         - ~/.phpenv/versions/7.2/bin/php -v
         - ~/.phpenv/versions/7.2/bin/phpunit --version  

    - name: u14ruball-test
      type: runSh
      runtime:
        container: true
      steps:
        - IN: u14all-image
        - TASK:
            runtime:
              options:
                imageName: "drydock/u14ruball"
                imageTag: master
            script:
             - source /etc/profile.d/rvm.sh
             - rvm list
             - ruby --version 

      - name: u14python-test
        type: runSh
        steps:
          - IN: u14all-image
          - TASK:
              runtime:
                options:
                  imageName: "drydock/u14pytall"
                  imageTag: master
              script:
                 - python --version          
                 - python2.7 -V            
                 - python3.4 -V
                 - python3.5 -V
                 - python3.6 -V
                 - python3.7 -V
                 - pip --version  

    - name: u14nodall
      type: runSh
      steps:
        - IN: u14all-image
        - TASK:
            runtime:
              options:
                imageName: "drydock/u14nodall"
                imageTag: master
            script:
            - grunt --version
            - mocha --version
            - vows --version
            - casperjs --version
            - bower --version
            - phantomjs --version
            - java -jar /srv/selenium-server-standalone-3.12.0.jar --version
            - node --version
            - nvm list
            - npm --version   

      - name: clojuretest
        type: runSh
        steps:
          - IN: u14all-image
          - TASK:
              runtime:
                options:
                  imageName: "drydock/u14cloall"
                  imageTag: master
              script:

                - echo "(print *clojure-version*)" > clojure.main   
                - clj clojure.main
                - java -jar /root/lib/clojure-1.8.0.jar clojure.main
                - java -jar /root/lib/clojure-1.7.0.jar clojure.main
                - java -jar /root/lib/clojure-1.6.0.jar clojure.main
                - java -jar /root/lib/clojure-1.5.1.jar clojure.main
                - java -jar /root/lib/clojure-1.4.0.jar clojure.main
                - java -jar /root/lib/clojure-1.3.0.jar clojure.main    

     - name: u14scala-test
       type: runSh
       steps:
         - IN: u14all-image
         - TASK:
             runtime:
               options:
                 imageName: "drydock/u14scaall"
                 imageTag: master
             script:
               - /usr/local/scala-2.12.6/bin/scala -version
               - /usr/local/scala-2.11.12/bin/scala -version 

     - name: u14javall-test
       type: runSh
       steps:
         - IN: u14all-image
         - TASK:
             runtime:
               options:
                 imageName: "drydock/u14javall"
                 imageTag: master
             script:
               - shipctl jdk set openjdk7
               - shipctl jdk set openjdk8
               - shipctl jdk set oraclejdk8
               - shipctl jdk set oraclejdk10
               - mvn --version
               - ant -version
               - gradle --version 

     - name: u14cppall-test
       type: runSh
       steps:
         - IN: u14all-image
         - TASK:
             runtime:
               options:
                 imageName: "drydock/u14cppall"
                 imageTag: master
             script:
              - gcc --version
              - autoconf --version
              - automake --version
              - ccache --version
              - clang --version           
