jobs:
  - name: u14-image
    type: runSh
    steps:
      - TASK:
          runtime:
            options:
              imageName: "drydock/u14"
              imageTag: master
          script:
            
             - java -version  
             - nodejs --version
             - yarn -version
             - source /usr/local/rvm/scripts/rvm
             - ruby -v
             - python -V
             - pip --version
             - virtualenv --version
             - git --version
             - aws --version
             - az --version
             - jfrog --version
             - gcloud version
             - git lfs version
             - kubectl version --client
             - kops version
             - helm version --client
             - doctl version
             - ansible --version
             - pip show boto
             - pip show boto3
             - pip show apache-libcloud
             - pip show azure
             - pip show dopy
             - packer --version
             - jq --version
             - terraform --version
             - openstack --version
             - eb --version
            
             
jobs:
  - name: u14all-image
    type: runSh
    steps:
      - IN: u14-image
      - TASK:
          runtime:
            options:
              imageName: "drydock/u14all"
              imageTag: master
          script:
         
            - elasticsearch --version
            - memcached --version
            - cassandra -v
            - riak version
            - service couchdb start
            - sleep 5
            - curl http://127.0.0.1:5984  
            - psql --version
            - java -jar /usr/local/selenium/selenium-server-standalone-3.11.0.jar --version
            - sqlite3 --version
            - mysql --version
            - mongod --version
            - /var/lib/neo4j/bin/neo4j version
            - dpkg -s rabbitmq-server | grep Version
            - redis-server --version
